# Generated by Django 4.0 on 2025-01-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0001_add_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
